### ISSUE TITLE
Pattern for graceful shutdown of node functions 

### ISSUE THREAD

**Issue by jldec** [projectriff/node-function-invoker#15]
In some scenarios, functions may want to maintain database connections or other handles which should be closed before shutdown in order to avoid leaks.

Is there a way to provide functions with an event hook to do this when function containers are shutdown?

e.g. this function opens a redis client connect
https://github.com/markfisher/s1p2017-faas-demo/blob/master/functions/vote-counter/vote-counter.js

**Comment by jldec** [comment]
here's one example (long-running node server but similar situation)
https://github.com/markfisher/s1p2017-faas-demo/blob/master/ui/server.js#L261

**Comment by scothis** [comment]
Yes, we should document this. The script that exports the function being invoked can listen for `SIGTERM` and then cleanup. I'm not sure if the invoker should provide any special support here, but if it becomes a common question we can re-evaluate.

For example:

```js
process.on('SIGTERM', () => {
  // do cleanup work
  process.exit(0);
});
```

**Comment by scothis** [comment]
As a result of #23, the invoker now listens for `SIGTERM` and `SIGINT` directly, so functions **should not** also listen for these signals. We'll need to introduce a special hook for functions to do cleanup work.

```js
module.exports = async () => {
  // the function
};

module.exports.$init = async () => {
  // do setup work
};

module.exports.$destroy = async () => {
  // do cleanup work
};
```

The `$init` and `$destroy` methods are optional, and only need to be implemented if there is work that needs to be completed before the function is invoked for the first time or before the process terminates, respectively.

The `$` prefix is commonly used to denote framework related hooks on otherwise user defined objects. It reduces the risk of another method accidentally existing with the same name on the target function.
