### ISSUE TITLE
Muted test reporter does not always mute test logs

### ISSUE THREAD

**Issue by fbiville** [projectriff/node-function-invoker#172]
Sometimes, `Promoting request-reply function to streaming function` is displayed.
This might be a misuse of Jasmine APIs in [the custom reporter](https://github.com/projectriff/node-function-invoker/blob/6ab7496afdd0d06755d6e4cf303533cdb1a4624a/spec/reporters/muted-console-reporter.js).

**Comment by fbiville** [comment]
If you have `nvm` installed with Node 10.x, 12.x and 13.x, you should be able to reproduce after 1 to several executions of [nvm_test_all.sh](https://github.com/projectriff/node-function-invoker/blob/f0e1e69ab5a9c0ee84471b186d3166cc2190d246/nvm_test_all.sh).

**Comment by Kehrlann** [comment]
This is because suites can be nested. So if you restore the console whenever you exit a suite, you will restore the console when exiting nested suites, and subsequent tests in the parent suite will have a "real" console.

For example, if you have:

```javascript
describe('outer', () => {
  it('test-one', () => {
    console.log('test-one');
  });

  describe('inner', () => {
    it('test-two', () => {
      console.log('test-two');
    });
  });
});
```

Sometimes Jasmine will do `test-one` then `test-two`, in that case you will see no output.
But when Jasmine does `test-two` first, it exists `inner`, restores the console and then runs `test-one` with a real console.

Submitting PR for this.
