### ISSUE TITLE
Investigate javascript event stream semantics

### ISSUE THREAD

**Issue by jldec** [projectriff/node-function-invoker#18]

**Comment by scothis** [comment]
After playing around with a few different idioms including: (async) generators, (async) iterators, event emitters and streams. I like the semantics of streams the best. While streams are not native to the JS language, they are prevalent in Node. There is an emerging standard for JS [Streams at WHATWG](https://streams.spec.whatwg.org/) that we should watch, however, it's not well supported in the wild right now.

Within Node Streams, there are two differrent approaches: a duplex stream and independent input and output streams. While independent streams require a little more ceremony (calling `output.end()`), they also enable use cases that are impossible with a duplex stream.

Most streams in Node operate on chunks of binary or string data. In this case, we're using Streams in object mode which allows passing non-null objects via the stream instead of Buffers and byte arrays. 

We'll continue to maintain the existing signature for request-reply methods, and could likely also use those methods as a simplified transformer.

### Some examples

Message sink:
```js
module.exports = (input, output) => {
    input.on('data', data => {
        // do something with the data
    });
    input.on('end', () => output.end());
};
```

Message source:
```js
module.exports = (input, output) => {
    output.write('message 1');
    output.write('message 2');
    ...
    output.write('message N');
    output.end();
};
```

Message transformer:
```js
const through2 = require('through2');
const uppercase = through2.obj((chunk, encoding, cb) => {
    try {
        cb(null, chunk.toUpperCase());
    } catch (err) {
        cb(err);
    }
});

module.exports = (input, output) => {
    // using .pipe() is beneficial as it maintains back pressure.
    input.pipe(uppercase).pipe(output);
};
```

Message reducer:
```js
// impossible with a duplex stream
module.exports = (input, output) => {
    let sum = 0;
    input.on('data', data => {
        sum += data;
    });
    input.on('end', () => {
        output.write(sum);
        output.end();
    });
};
```

**Comment by jldec** [comment]
Yeah, i like that too - very nicely exposes/illuminates different stream patterns without too much magic.

Do you know if there is a newer (maybe 'async', non cb) equivalent to through2? That library feels a bit old. I'm worried that we would be recommending through2 as the best way to turn regular JS functions into streams.

**Comment by jldec** [comment]
history of through2
http://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

**Comment by scothis** [comment]
If you thought `through2` looked crufty, don't ever try to create a stream by hand.

The function passed to `ps.map()` can also be async.

```js
const ps = require('promise-streams');
const uppercase = ps.map(chunk => chunk.toUpperCase());

module.exports = (input, output) => {
    // using .pipe() is beneficial as it maintains back pressure.
    input.pipe(uppercase).pipe(output);
};
```

**Comment by MichalCz** [comment]
Maybe you would be interested in using [scramjet](https://github.com/signicode/scramjet)? It's way faster than through2 and still supported. Plus it has a simple API and ships with multi threading.
