### ISSUE TITLE
Is custom status code in response possible?

### ISSUE THREAD

**Issue by kapolos** [projectriff/node-function-invoker#183]
What is the proper way to send a non-200 response from a node function? The `@projectriff/message` doesn't seem to provide this or am I perhaps missing something obvious? 

My use-case is that I want to use a riff function as an action handler for a service that expects a response like this:

```
{
  "message": "<mandatory error message>",
  "code": "<optional error code>"
}
```

with a 4xx status code.

**Comment by scothis** [comment]
riff functions are geared towards message processing. The function invokers are decoupled from the underlaying protocol and actually speak a [flavor of gRPC](https://github.com/projectriff/invoker-specification/blob/master/streaming.md) rather than HTTP. Because HTTP is so common, we embed [an adapter](https://github.com/projectriff/streaming-http-adapter) into the same image so that it appears to speak HTTP natively. There are several aspects of HTTP that are currently lost in the conversion to messages including the method, path and response status. The HTTP headers and entity survive.

We could look at exposing more of the HTTP semantics within the HTTP function invocation spec.

cc @fbiville

**Comment by kapolos** [comment]
Thank you very much for the clarifications @scothis ! I understand now. I'll add an express server as a "front-end" to translate messages to full HTTP responses as needed. Of course having this functionality of riff itself would be awesome but I'm not sure how easy this is to be added given the architecture - still, crossing fingers :)

**Comment by scothis** [comment]
Hopefully we can handle this within the existing [streaming-http-adapter](https://github.com/projectriff/streaming-http-adapter). I'd image something like:

- request method -> `x-http-method` message header
- request path -> `x-http-path` message header
- request version -> `x-http-version` message header
- `x-http-status` message header -> http status code

We've been hesitant to offer something like this in the past because we wanted to emphasize that riff is primarily a platform for stateful stream processing. That hard line is softening, however, we still want to avoid turning a function programming model into an application programming model.

**Comment by scothis** [comment]
Upstream https://github.com/projectriff/streaming-http-adapter/issues/44

**Comment by scothis** [comment]
This behavior is now in the `projectriff/builder: 0.6.0-snapshot-20200420200944-547d1659a229136a` builder image.

A sample function that controls its status code:

```js
const { Message } = require("@projectriff/message");

module.exports = (input) => {
  return Message.builder()
    .replaceHeader("x-http-status", input)
    .payload(input)
    .build();
};
```


```sh
$ curl http://localhost:8080 -v -H 'Content-Type: text/plain' -w'\n' -d 202
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: text/plain
> Content-Length: 3
> 
* upload completely sent off: 3 out of 3 bytes
< HTTP/1.1 202 Accepted
< Content-Type: text/plain
< X-Http-Status: 202
< Date: Mon, 20 Apr 2020 20:30:32 GMT
< Content-Length: 3
< 
* Connection #0 to host localhost left intact
202
* Closing connection 0
```

We still restrict the request to `POST /`, but may relax that in the future.
